site_name: Meng's Docs
site_url: ""
use_directory_urls: false
plugins: [] 
markdown_extensions:
  - extra
  - toc: 
      permalink: true
  - pymdownx.arithmatex:
      generic: true
extra_javascript:
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
  - 'https://polyfill.io/v3/polyfill.min.js?features=es6'
  - 'https://cdn.jsdeliver.net/npm/mathjax@3/es5/tex-mnl-chtml.js'
nav:
  - Home: index.md
  - myCodes:
      - 'Snippets': './Snippets/led_blinks.md'
      - 'NAI-24 Code': './Snippets/nai_24_code.md'
  - myNotes:
      - 'Markdown Cheat Sheet': './myNotes/markdown_cheat_sheet.md'
      - 'compressor': ./myNotes/nlive_24_compressor.md
  - About: about.md
